Update protect-main.yml
temp allow dir push to main

diff --git a/.github/workflows/protect-main.yml b/.github/workflows/protect-main.yml
--- a/.github/workflows/protect-main.yml
+++ b/.github/workflows/protect-main.yml
@@ -1,15 +1,15 @@
-name: Protect Main Branch
+# name: Protect Main Branch
 
-on:
-  push:
-    branches:
-      - main
+# on:
+#   push:
+#     branches:
+#       - main
 
-jobs:
-  block_direct_push:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Block Direct Push
-        run: |
-          echo "ERROR: Direct pushes to main are not allowed!"
-          exit 1
+# jobs:
+#   block_direct_push:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Block Direct Push
+#         run: |
+#           echo "ERROR: Direct pushes to main are not allowed!"
+#           exit 1
